platform :ios, '10.0'

use_frameworks!
#inhibit_all_warnings!
install! 'cocoapods',
:generate_multiple_pod_projects => true


target 'Example' do
    pod 'Droste', :path => '../', :testspecs => ['Tests'] 
end
