language: objective-c
osx_image: xcode9.3
env:
- DESTINATION="OS=11.1,name=iPhone 7" SCHEME="Example" SDK=iphonesimulator
podfile: Example/Podfile

before_install: 
- gem uninstall cocoapods --all -aIx
- gem install cocoapods

script:
- pod lib lint --allow-warnings --verbose
