language: objective-c
osx_image: xcode9.1
env:
- DESTINATION="OS=11.1,name=iPhone 7" SCHEME="Example" SDK=iphonesimulator
podfile: Example/Podfile

before_install: 
- rm Example/Podfile.lock
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Example.xcworkspace -destination "${DESTINATION}" -scheme ${SCHEME} -sdk ${SDK} ONLY_ACTIVE_ARCH=NO | xcpretty
