language: objective-c
osx_image: xcode11.3
env:
- DESTINATION="OS=13.3,name=iPhone 11" SCHEME="Example" SDK=iphonesimulator
podfile: Example/Podfile

before_install:
- gem uninstall cocoapods --all -aIx
- gem install cocoapods

script:
- pod lib lint --allow-warnings --verbose
